-- MySQL Script generated by MySQL Workbench
-- Tue Dec 18 13:53:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hover_academic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hover_academic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hover_academic` DEFAULT CHARACTER SET utf8 ;
USE `hover_academic` ;

-- -----------------------------------------------------
-- Table `hover_academic`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `us_nome` VARCHAR(60) NOT NULL,
  `us_login` VARCHAR(45) NOT NULL unique,
  `us_senha` VARCHAR(45) NOT NULL,
  `us_cargo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`responsavel` (
  `id_responsavel` INT NOT NULL AUTO_INCREMENT,
  `res_nome` VARCHAR(70) NOT NULL,
  `res_data_nascimento` DATE NOT NULL,
  `res_rg` VARCHAR(20) NOT NULL unique,
  `res_cpf` VARCHAR(11) NOT NULL unique,
  PRIMARY KEY (`id_responsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`alunos` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id_usuario` INT NOT NULL,
  `responsavel_id_responsavel` INT NULL,
  `al_nome` VARCHAR(70) NOT NULL,
  `al_data_nascimento` DATE NULL,
  `al_rg` VARCHAR(20) NULL unique,
  `al_cpf` VARCHAR(11) NULL unique,
  `al_sexo` CHAR(1) NULL,
  `al_obs` VARCHAR(255) NULL,
  `al_status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_aluno`),
  FOREIGN KEY (`usuarios_id_usuario`)
  REFERENCES `hover_academic`.`usuarios` (`id_usuario`),
  FOREIGN KEY (`responsavel_id_responsavel`)
  REFERENCES `hover_academic`.`responsavel` (`id_responsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`financeiro` (
  `id_financiro` INT NOT NULL AUTO_INCREMENT,
  `alunos_id_aluno` INT NOT NULL,
  `fin_num_parcelas` INT NOT NULL,
  `fin_valor` DECIMAL(5) NOT NULL,
  `fin_matricula` DECIMAL(5) NOT NULL,
  `fin_data_inicio` DATE NOT NULL,
  `fin_vencimento` DATE NOT NULL,
  `fin_taxa_juros` DOUBLE(4,2) NOT NULL,
  `fin_multa` DOUBLE(5,2) NOT NULL,
  PRIMARY KEY (`id_financiro`),
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `hover_academic`.`alunos` (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`cancelamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`cancelamento` (
  `financeiro_id_financiro` INT NOT NULL,
  `can_data` DATE NOT NULL,
  `can_valor` DOUBLE NOT NULL,
  PRIMARY KEY (`financeiro_id_financiro`),
    FOREIGN KEY (`financeiro_id_financiro`)
    REFERENCES `hover_academic`.`financeiro` (`id_financiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`parcelas` (
  `financeiro_id_financiro` INT NOT NULL,
  `par_numero` INT NOT NULL,
  `par_valor` DOUBLE(5,2) NOT NULL,
  `par_juros` DOUBLE(5,2) NULL,
  `par_multa` DOUBLE(5,2) NULL,
  `par_data_pagamento` DATE NOT NULL,
  PRIMARY KEY (`financeiro_id_financiro`, `par_numero`),
    FOREIGN KEY (`financeiro_id_financiro`)
    REFERENCES `hover_academic`.`financeiro` (`id_financiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`cursos` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `cur_nome` VARCHAR(30) NOT NULL unique,
  `cur_nivel` VARCHAR(15) NOT NULL,
  `cur_duracao` INT NOT NULL,
  `cur_valor` DOUBLE NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id_usuario` INT NOT NULL,
  `curos_id_curso` INT NOT NULL,
  `tur_nome` VARCHAR(30) NOT NULL unique,
  `tur_dia` VARCHAR(15) NOT NULL,
  `tur_horario` TIME NOT NULL,
  `tur_data_inicio` DATE NOT NULL,
  PRIMARY KEY (`id_turma`),
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `hover_academic`.`usuarios` (`id_usuario`),
    FOREIGN KEY (`curos_id_curso`)
    REFERENCES `hover_academic`.`cursos` (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`alunos_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`alunos_turma` (
  `id_aluno_turma` INT NOT NULL AUTO_INCREMENT,
  `turma_id_turma` INT NOT NULL,
  `alunos_id_aluno` INT NOT NULL,
  PRIMARY KEY (`id_aluno_turma`),
    FOREIGN KEY (`turma_id_turma`)
    REFERENCES `hover_academic`.`turma` (`id_turma`),
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `hover_academic`.`alunos` (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`boletim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`boletim` (
  `id_boletim` INT NOT NULL AUTO_INCREMENT,
  `alunos_turma_id_aluno_turma` INT NOT NULL,
  `bo_av1` DOUBLE(4,2) NULL,
  `bo_av2` DOUBLE(4,2) NULL,
  `bo_av3` DOUBLE(4,2) NULL,
  `bo_av4` DOUBLE(4,2) NULL,
  PRIMARY KEY (`id_boletim`),
    FOREIGN KEY (`alunos_turma_id_aluno_turma`)
    REFERENCES `hover_academic`.`alunos_turma` (`id_aluno_turma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`frequencia` (
  `id_frequencia` INT NOT NULL AUTO_INCREMENT,
  `alunos_turma_id_aluno_turma` INT NOT NULL,
  `fre_data` DATE NOT NULL,
  PRIMARY KEY (`id_frequencia`),
    FOREIGN KEY (`alunos_turma_id_aluno_turma`)
    REFERENCES `hover_academic`.`alunos_turma` (`id_aluno_turma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`contatos` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `alunos_id_aluno` INT NOT NULL,
  `con_telefone` INT(11) NOT NULL,
  `con_celular` INT(11) NULL,
  `con_email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_contato`),
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `hover_academic`.`alunos` (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hover_academic`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hover_academic`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `alunos_id_aluno` INT NOT NULL,
  `end_rua` VARCHAR(45) NOT NULL,
  `end_numero` INT(6) NOT NULL,
  `end_bairro` VARCHAR(45) NOT NULL,
  `end_cidade` VARCHAR(45) NOT NULL,
  `end_estado` VARCHAR(45) NULL,
  `end_cep` INT(8) NULL,
  PRIMARY KEY (`id_endereco`),
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `hover_academic`.`alunos` (`id_aluno`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
